/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 room.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-3.87, 0.53, -0.09]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.82, 0.5, 3.6]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[1.44, 1.34, -0.1]} scale={[1, 1, 3.34]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-0.56, 1.47, -1.72]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.79, 1, 1]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-0.57, 1.48, 1.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.79, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/room.glb')
