/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 trash.glb --transform
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Trash(props) {
  const [hovered, hover] = useState(false)

  const { nodes, materials } = useGLTF('/trash-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.98, 2.19, -14.72]} rotation={[-Math.PI, 0, 0]} onPointerOver={(event) => hover(true)}
        onPointerOut={(event) => hover(false)}> 
      <meshStandardMaterial color={hovered ? '#4e805b' : '#84c294'} /> 
    </mesh>
    </group>
  )
}

useGLTF.preload('/trash-transformed.glb')
